theme: jekyll-theme-midnight
title: Pag. Web personal
description: En esta pagina web expondre mis avances de aprendizaje y un enlace a un cirruculum vitae profecional ademas de un maletin de proyectos 
